[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

[build]
target = "xtensa-esp32-none-elf"
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

[unstable]
build-std = ["core", "alloc"]
